# Copyright 2026 Ramiz Gindullin.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Description:  Various supplementary utilities related to I/O operations
#
# Authors: Ramiz GINDULLIN (ramiz.gindullin@it.uu.se)
# Version: 1.3.4
# Last Revision: March 2026
#


import os
import datetime
import logging

from matplotlib.figure import Figure
from matplotlib.backends.backend_pdf import PdfPages
from typing import List, Union, Tuple, Optional

from core.layout_utils import transform_index, transform_coordinate, find_all_plates_concentrations
from models.constants import Performance, Alphabet, Validation, PathsIni, Visualization, FileTypes, PlaterFormat, FigureProperties
from models.dto import CSVConversionRequest


logger = logging.getLogger(__name__)


def save_figure_to_path(
    figure: Figure,
    path: str,
    material_scales: Optional[List[Figure]] = None
) -> None:
    """Write a single figure to disk as PNG or PDF.

    Args:
        figure: Matplotlib figure to save
        path: Full destination path (extension determines format)
        material_scales: Additional figures to append when saving as PDF

    Raises:
        IOError: If the file cannot be written
    """
    if material_scales is None:
        material_scales = []

    if path.lower().endswith('.pdf'):
        with PdfPages(path) as pdf:
            pdf.savefig(figure, dpi=FigureProperties.DPI, bbox_inches='tight')
            for fig in material_scales:
                pdf.savefig(fig, dpi=FigureProperties.DPI, bbox_inches='tight')
            d = pdf.infodict()
            d['Title'] = 'Microplate Layout Visualizations'
            d['Author'] = 'MPLACE'
            d['Subject'] = 'Plate layouts generated by MPLACE'
            d['CreationDate'] = datetime.datetime.now()
    else:
        figure.savefig(path, dpi=FigureProperties.DPI, bbox_inches='tight')


def save_figures_to_pdf(
    figures: List[Tuple[Figure, str]],
    path: str,
    material_scales: Optional[List[Figure]] = None
) -> None:
    """Write multiple figures into a single PDF file.

    Args:
        figures: List of tuples (figure, figure filename template)
        path: Full destination path
        material_scales: Additional figures to append at the end

    Raises:
        IOError: If the file cannot be written
    """
    if material_scales is None:
        material_scales = []

    with PdfPages(path) as pdf:
        for fig, _ in figures:
            pdf.savefig(fig, dpi=FigureProperties.DPI, bbox_inches='tight')
        for fig in material_scales:
            pdf.savefig(fig, dpi=FigureProperties.DPI, bbox_inches='tight')
        d = pdf.infodict()
        d['Title'] = 'Microplate Layout Visualizations'
        d['Author'] = 'MPLACE'
        d['Subject'] = 'Plate layouts generated by MPLACE'
        d['CreationDate'] = datetime.datetime.now()


def save_csv_to_path(csv_lines: Union[List[str], str], path: str) -> None:
    """Write CSV content to disk.

    Args:
        csv_lines: List of lines or a single string
        path: Full destination path

    Raises:
        IOError: If the file cannot be written
    """
    with open(path, 'w', encoding='utf-8') as f:
        if isinstance(csv_lines, list):
            f.writelines(csv_lines)
        else:
            f.write(csv_lines)


def read_csv_file(file_path: str) -> List[str]:
    """Read CSV file and return all lines except header.
    
    Args:
        file_path: Path to the CSV file
        
    Returns:
        List of lines from CSV file (excluding header)
        
    Raises:
        FileNotFoundError: If file cannot be read
        ValueError: If CSV format is neither PharmBio nor valid Plater format
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            layout_text_array = file.readlines()
        
        layout_text_array = convert_to_pharmbio_format(layout_text_array)
        
        line_count = len(layout_text_array)
        logger.info(f"CSV file loaded: {file_path}, {line_count} data lines")
        return layout_text_array
    except (ValueError) as e:
        logger.error(f"Failed to read CSV file: {file_path}, error: {e}")
        raise e
    except (FileNotFoundError, IOError) as e:
        logger.error(f"Failed to read CSV file: {file_path}, error: {e}")
        raise FileNotFoundError(f"Could not read CSV file: {file_path}") from e
    

def convert_to_pharmbio_format(layout_text_array: List[str]) -> List[str]:
    """Verifies that the uploaded data is in the PharmBio format.
    If it is in the Plater format, the function will convert it into PharmBio format
    
    Args:
        layout_text_array: List of lines from CSV file (including header)
        
    Returns:
        List of lines from CSV file (excluding header)
        
    Raises:
        ValueError: If the file format is neither PharmBio nor valid Plater
    """
    header = layout_text_array[0].strip().split(',')
    
    if len(header) == 6 and [x.strip() for x in header] == ['plateID', 'well', 'cmpdname', 'CONCuM', 'cmpdnum', 'VOLuL']:
        logger.info(f"CSV file (PharmBio format) is recognized")
        return layout_text_array[1:]
    else:
        # For simplicity, currently we assume that we can only load a Plater formatted file
        # We also assume that the file in the Plater format will always have 2 matrices: Drugs and Concentrations
        try:
            rows, cols, drugs_matrix, concentrations_matrix = scan_csv_plater_matrices(layout_text_array)
            logger.info(f"CSV file (Plater format) is recognized and parsed")
            
            plater_layout_text_array = []
            
            for i in range(rows):
                for j in range(1,cols):
                    if drugs_matrix[i][j] != '':
                        # VOLuL column always empty as we do not store VOLuL column in Plater format
                        plater_layout_text_array.append(''.join(['plate_1',
                                                                 ',',
                                                                 drugs_matrix[i][0] + "{:02d}".format(j),
                                                                 ',',
                                                                 drugs_matrix[i][j],
                                                                 ',',
                                                                 concentrations_matrix[i][j],
                                                                 ',',
                                                                 drugs_matrix[i][j] + '_' + concentrations_matrix[i][j],
                                                                 ','
                                                                 ]))
            
            return plater_layout_text_array
        except ValueError:
            raise
        except Exception as e:
            logger.error(f"File could not be read in Plater format, error: {e}")
            raise ValueError(f"CSV file format unrecognized: {e}") from e
        
def scan_csv_plater_matrices(layout_text_array: List[str]) -> Tuple[int, int, List[str],List[str]]:
    """Scans the CSV file (Plater format) and extracts the layout information about the placement
    of drugs and compounds
    
    Args:
        layout_text_array: List of lines from CSV file (including header)
        
    Returns:
        Dimensions of the extracted layout (number of rows and columns)
        Lists of lines corresponding to drug and concentrations
        
    Raises:
        ValueError: If file cannot be read
    """
    drugs_matrix: List[str] = []
    concentrations_matrix: List[str] = []
    
    # Removing the blank lines (line == '\n' happens on Windows machines)
    layout_text_array = [line for line in layout_text_array if line.strip() != '' and line.strip() != '\n']
    
    cols = len(layout_text_array[0].split(','))
    
    is_drugs = False
    is_concentrations = False
    done_drugs = False
    done_concentrations = False
    matrix_count = 0
    
    current_section = ''
    
    for line in layout_text_array:
        elements = line.strip().split(',')
        
        if len(elements) != cols:
            raise ValueError(f'CSV Plater file has formatting issues (number of column for line {line} is not equal to {cols})')
        
        if is_drugs and elements == ['' for _ in range(cols)]:
            is_drugs = False
            done_drugs = True
        
        if is_concentrations and elements == ['' for _ in range(cols)]:
            is_concentrations = False
            done_concentrations = True
        
        if elements[0] == PlaterFormat.DRUGS_LABEL:
            is_drugs = True
            matrix_count += 1
            current_section = 'drugs'
        elif is_drugs:
            drugs_matrix.append(elements)
            
        if elements[0] == PlaterFormat.CONCENTRATIONS_LABEL:
            is_concentrations = True
            matrix_count += 1
            current_section = 'concentrations'
        elif is_concentrations:
            concentrations_matrix.append(elements)
            
        if elements[0] == PlaterFormat.DRUGS_LABEL or elements[0] == PlaterFormat.CONCENTRATIONS_LABEL:
            for i in range(1,cols):
                if elements[i] != str(i):
                    raise ValueError(f'CSV Plater file has formatting issues (header line for {current_section} has incorrect order of columns)')
    
    # When reached EOF
    if is_drugs:
        done_drugs = True
    if is_concentrations:
        done_concentrations = True
    
    # Data verification:
    if matrix_count < 2 or not done_drugs or not done_concentrations:
        raise ValueError(f'CSV Plater file has formatting issues (no layout matrix for drugs or concentrations)')
    if matrix_count > 2:
        raise ValueError(f'CSV Plater file has formatting issues (too many layout matrices for drugs/concentrations)')
    
    rows = len(drugs_matrix)
    if rows != len(concentrations_matrix):
        logger.info('Drugs:')
        for line in drugs_matrix:
            logger.info(line)
        logger.info('Concentrations:')
        for line in concentrations_matrix:
            logger.info(line)
        raise ValueError(f'Drug and concentration layouts of Plater file have mismatched number of rows: {rows} and {len(concentrations_matrix)}')
    
    return rows, cols, drugs_matrix, concentrations_matrix


def path_truncate(path: str) -> str:
    """Truncate path.
    
    Args:
        path: File path to display
    
    Returns:
        truncated path
    """
    if len(path) >= Validation.PATH_DISPLAY_MAX_LENGTH:
        prefix = Validation.PATH_TRUNCATION_PREFIX
    else:
        prefix = ''
    return prefix + path[-Validation.PATH_DISPLAY_MAX_LENGTH:]


def extract_csv_text(text: str) -> List[str]:
    """Extract CSV content from MiniZinc output.
    
    Args:
        text: MiniZinc output text
        
    Returns:
        List of CSV lines extracted from output
    """
    s, e = None, None
    lines = text.split('\n')

    for i in range(len(lines)):
        if lines[i] == '=====UNSATISFIABLE=====':
             raise RuntimeError(
                'The model is unsatisfiable (no layout can be constructed).\n'
                'Recommendation: relax some constraints or change the input data.'
                )
        if lines[i] == 'plateID,well,cmpdname,CONCuM,cmpdnum,VOLuL':
            s = i
        if lines[i][:17] == 'criteria function' or lines[i][:1] == '%' or lines[i] == '----------' or lines[i] == 'finished':
            if e is None or (s is not None and e <= s):
                e = i
    
    if s is None:
        raise ValueError('CSV header not found in MiniZinc output.')
    if e is None:
        e = len(lines)
    elif e <= s:
        e = len(lines)
    
    extracted_lines = [line + '\n' for line in lines[s:e]]
    logger.debug(f"Extracted {len(extracted_lines)} CSV lines from MiniZinc output")
    return extracted_lines


def convert_pharmbio_to_plater(input_data: CSVConversionRequest) -> List[str]:
    """Convert CSV-formatted text from PharmBio format to Plater format
    
    Args:
        input_data: CSVConversionRequest() object containing all input data
        
    Returns:
        List of CSV lines compatible with Plater R-package
    """
    rows = int(input_data.rows)
    cols = int(input_data.cols)
    lines = input_data.csv_lines
    plates, _ = find_all_plates_concentrations(lines)
    return [convert_pharmbio_to_plater_plate(CSVConversionRequest(csv_lines=plates[plate],
                                                                  rows=rows,
                                                                  cols=cols)) for plate in plates]


def convert_pharmbio_to_plater_plate(input_data: CSVConversionRequest) -> str:
    """Convert CSV-formatted text from PharmBio format to Plater format
    
    Args:
        input_data: CSVConversionRequest() object containing all input data
        
    Returns:
        List of CSV lines compatible with Plater R-package
    """
    rows = int(input_data.rows)
    cols = int(input_data.cols)
    lines = input_data.csv_lines
    
    drugs_matrix = [['' for j in range(cols+1)] for i in range(rows+1)]
    concentration_matrix = [['' for j in range(cols+1)] for i in range(rows+1)]
    
    drugs_matrix[0][0] = PlaterFormat.DRUGS_LABEL
    concentration_matrix[0][0] = PlaterFormat.CONCENTRATIONS_LABEL
    
    for i in range(rows):
        drugs_matrix[i+1][0] = transform_index(i)
        concentration_matrix[i+1][0] = transform_index(i)
    
    for i in range(1,cols+1):
        drugs_matrix[0][i] = str(i)
        concentration_matrix[0][i] = str(i)
    
    for line in lines:
        x,y = transform_coordinate(line[0])
        drugs_matrix[x+1][y+1] = line[1]
        concentration_matrix[x+1][y+1] = line[2]
        
    text: str = plater_matrix_to_string(drugs_matrix)
    text += ''.join([',' for _ in range(cols)]) + '\n'
    text += plater_matrix_to_string(concentration_matrix)
    
    return text    


def plater_matrix_to_string(matrix: List[List[str]]) -> str:
    """Convert a Plater matrix into a CSV-formatted string.

    Each row is joined with commas, with rows separated by newlines.
    The last element in each row is written without a trailing comma.

    Args:
        matrix: 2D list of strings representing the Plater layout,
                where matrix[0] is the header row (label + column indices)
                and matrix[i][0] is the row label (e.g. 'A', 'B', ...).

    Returns:
        A single string of CSV-formatted lines ready to write to disk,
        with each row terminated by a newline character.
    """
    text: str = ''
    for line in matrix:
        for element in line[:-1]:
            text += element + ','
        text += line[-1] + '\n'
    return text
